AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Todo API for Amplify

Parameters:

  BranchName:
    Description: the gitbranch name
    Type: String
  
  AmplifyAppId:
    Description: the app id assigned by amplify
    Type: String
    DefaultValue: d3q98mpsf57reu

Globals:
  Function:
    Timeout: 600

Resources:

  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      BranchName: !Ref BranchName
      AppId: !Ref AmplifyAppId
      EnableAutoBuild: true
  
  ExpressFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: todos/
      Handler: lambda.handler
      Runtime: nodejs14.x
      MemorySize: 1024
      Events:
        ExpressFunctionProxy:
          Type: Api
          Properties:
            Path: '/{proxy+}'
            Method: ANY
        ExpressFunctionRoot:
          Type: Api
          Properties:
            Path: '/'
            Method: ANY

Outputs:

  TodoApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ApiGW}.execute-api.${AWS::Region}.amazonaws.com/prod/"
